Repository hassio-addons/addon-nginx-proxy-manager, pull requests merged in 2021-02, with the labels that each got.

#146 Upgrade add-on base image to 9.1.2
  proxy-manager/Dockerfile
  proxy-manager/build.json
Labels: dependencies

#147 🔨 Change to addon.option for reset_database
  proxy-manager/rootfs/etc/cont-init.d/mysql.sh
Labels: refactor

#153 :arrow_up: Upgrades NGINX Proxy Manager to v2.8.0
  proxy-manager/Dockerfile
Labels: dependencies, minor

#155 :arrow_up: Upgrades git to 2.30.1-r0
  proxy-manager/Dockerfile
Labels: dependencies

#160 Upgrade add-on base image to 9.1.4
  proxy-manager/Dockerfile
  proxy-manager/build.json
Labels: dependencies

#162 :arrow_up: Upgrades python3 to 3.8.7-r1
  proxy-manager/Dockerfile
Labels: dependencies
