Repository hassio-addons/addon-nginx-proxy-manager, pull requests merged in 2023-03, with the labels that each got.

#408 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  proxy-manager/.README.j2
  proxy-manager/DOCS.md
Labels: maintenance

#411 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  proxy-manager/Dockerfile
Labels: maintenance

#429 Fix NPM build with NodeJS 18x
  proxy-manager/Dockerfile
Labels: bugfix

#399 Updated icon and logo
  proxy-manager/icon.png
  proxy-manager/logo.png
Labels: maintenance

#430 Fix broken URL
  proxy-manager/DOCS.md
Labels: documentation
